version: '2' 

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - 50070:50070
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    depends_on: 
      - namenode
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    ports:
      - 50075:50075

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    env_file:
      - ./hadoop-hive.env
    environment:
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore
    ports:
      - 10000:10000
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    ports:
      - 9083:9083
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0

  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - ./hadoop-hive.env
    depends_on:
      - hive-server
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
      - HADOOP_CONF_DIR=/etc/hadoop/conf
    volumes:
      # - /home/wtcrow/shared/spark:/shared/  # replace first item by your shared folder for spark files
      - ./spark_conf/hadoop:/etc/hadoop/conf/
      - ./spark_conf/hive:/spark/conf/
  spark-worker:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
      - HADOOP_CONF_DIR=/etc/hadoop/conf
    ports:
      - "8081:8081"
    env_file:
      - ./hadoop-hive.env
    volumes:
      - ./spark_conf/hadoop:/etc/hadoop/conf/
      - ./spark_conf/hive:/spark/conf/

  jupyter:
    image: jupyter/pyspark-notebook:dd2087c75645
    container_name: jupyter
    env_file:
      - ./hadoop-hive.env
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
      - HADOOP_CONF_DIR=/etc/hadoop/conf
    ports:
      - "8888:8888"
    depends_on:
      - spark-master
    volumes:
      - ./spark_conf/hadoop:/etc/hadoop/conf/
      - ./spark_conf/hive:/usr/local/spark/conf
      # - /home/wtcrow/shared/jupyter:/home/jovyan/work  # replace first item by your shared folder for jupyter files
    working_dir: /home/jovyan/work

volumes:
  namenode:
  datanode:
